version: 2
updates:
  - package-ecosystem: "pip" # or "pip", "maven", etc.
    directory: "/"           # Location of package manifests
    schedule:
      interval: "weekly"     # Can be "daily", "weekly", or "monthly"
